version: '3.3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel
    restart: always
    tty: true
    environment:
      SERVICE_NAME: laravel
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./laravel-dev:/var/www
       - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: always
    tty: true
    ports:
      - "8888:80"
        #  - "4431:443"
    volumes:
      - ./laravel-dev:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-network

  #MySQL Service
  db:
    image: mysql:8.0.17
    container_name: laravel-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123456@laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - laraveldata:/var/lib/mysql
    networks:
      - laravel-network

  #adminer for db access
  adminer:
    image: adminer:latest
    restart: unless-stopped
    container_name: laravel-adminer
    ports:
      - 8800:8080

#Docker Networks
networks:
  laravel-network:
    driver: bridge

#Volumes
volumes:
  laraveldata:
    driver: local 

